# Generated by Django 2.2.16 on 2020-10-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
    ]
