# Generated by Django 2.2.16 on 2020-10-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
